// Code generated by protoc-gen-go. DO NOT EDIT.
// source: options/options.proto

package options // import "github.com/x-mod/options"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceOption struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceOption) Reset()         { *m = ServiceOption{} }
func (m *ServiceOption) String() string { return proto.CompactTextString(m) }
func (*ServiceOption) ProtoMessage()    {}
func (*ServiceOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_options_d94d1d758e06b448, []int{0}
}
func (m *ServiceOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceOption.Unmarshal(m, b)
}
func (m *ServiceOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceOption.Marshal(b, m, deterministic)
}
func (dst *ServiceOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceOption.Merge(dst, src)
}
func (m *ServiceOption) XXX_Size() int {
	return xxx_messageInfo_ServiceOption.Size(m)
}
func (m *ServiceOption) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceOption.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceOption proto.InternalMessageInfo

func (m *ServiceOption) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type HttpOption struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpOption) Reset()         { *m = HttpOption{} }
func (m *HttpOption) String() string { return proto.CompactTextString(m) }
func (*HttpOption) ProtoMessage()    {}
func (*HttpOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_options_d94d1d758e06b448, []int{1}
}
func (m *HttpOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpOption.Unmarshal(m, b)
}
func (m *HttpOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpOption.Marshal(b, m, deterministic)
}
func (dst *HttpOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpOption.Merge(dst, src)
}
func (m *HttpOption) XXX_Size() int {
	return xxx_messageInfo_HttpOption.Size(m)
}
func (m *HttpOption) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpOption.DiscardUnknown(m)
}

var xxx_messageInfo_HttpOption proto.InternalMessageInfo

func (m *HttpOption) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HttpOption) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

var E_Service = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ServiceOption)(nil),
	Field:         91020818,
	Name:          "options.service",
	Tag:           "bytes,91020818,opt,name=service",
	Filename:      "options/options.proto",
}

var E_Http = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*HttpOption)(nil),
	Field:         91020819,
	Name:          "options.http",
	Tag:           "bytes,91020819,opt,name=http",
	Filename:      "options/options.proto",
}

func init() {
	proto.RegisterType((*ServiceOption)(nil), "options.ServiceOption")
	proto.RegisterType((*HttpOption)(nil), "options.HttpOption")
	proto.RegisterExtension(E_Service)
	proto.RegisterExtension(E_Http)
}

func init() { proto.RegisterFile("options/options.proto", fileDescriptor_options_d94d1d758e06b448) }

var fileDescriptor_options_d94d1d758e06b448 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x2f, 0x28, 0xc9,
	0xcc, 0xcf, 0x2b, 0xd6, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x94, 0x42, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x38, 0xa9, 0x34, 0x4d, 0x3f, 0x25,
	0xb5, 0x38, 0xb9, 0x28, 0xb3, 0xa0, 0x24, 0xbf, 0x08, 0xa2, 0x54, 0x49, 0x93, 0x8b, 0x37, 0x38,
	0xb5, 0xa8, 0x2c, 0x33, 0x39, 0xd5, 0x1f, 0xac, 0x47, 0x48, 0x82, 0x8b, 0xbd, 0x2c, 0xb5, 0xa8,
	0x38, 0x33, 0x3f, 0x4f, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc6, 0x55, 0x32, 0xe3, 0xe2,
	0xf2, 0x28, 0x29, 0x29, 0x80, 0xaa, 0x13, 0xe3, 0x62, 0xcb, 0x4d, 0x2d, 0xc9, 0xc8, 0x4f, 0x81,
	0x2a, 0x83, 0xf2, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x32, 0x25, 0x98, 0xc0, 0x82, 0x20, 0xa6,
	0x55, 0x08, 0x17, 0x7b, 0x31, 0xc4, 0x0a, 0x21, 0x79, 0x3d, 0x88, 0x83, 0xf4, 0x60, 0x0e, 0xd2,
	0x43, 0xb1, 0xbc, 0x58, 0x62, 0xd2, 0x9e, 0xcd, 0xda, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x62, 0x7a,
	0x30, 0x2f, 0xa1, 0xa8, 0x08, 0x82, 0x19, 0x65, 0xe5, 0xc5, 0xc5, 0x92, 0x51, 0x52, 0x52, 0x20,
	0x24, 0x87, 0x61, 0xa4, 0x2f, 0xd8, 0x21, 0x30, 0x13, 0x27, 0xc3, 0x4c, 0x14, 0x86, 0x9b, 0x88,
	0xf0, 0x45, 0x10, 0xd8, 0x0c, 0x27, 0xa9, 0x28, 0x89, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd,
	0xe4, 0xfc, 0x5c, 0xfd, 0x0a, 0xdd, 0xdc, 0xfc, 0x14, 0x58, 0x88, 0x26, 0xb1, 0x81, 0xcd, 0x35,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x0c, 0x95, 0x6a, 0x6b, 0x01, 0x00, 0x00,
}
